name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      working-directory: ./workspace

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./workspace/yarn.lock

      - name: yarn install
        run: |
          yarn install
        working-directory: ${{ env.working-directory }}
      - name: prisma init
        run: |
          yarn prisma:generate
        working-directory: ${{ env.working-directory }}
      - name: yarn test
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          yarn build
          yarn test
        working-directory: ${{ env.working-directory }}