name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./workspace

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          yarn run package
          yarn run lint
          yarn exec tsc
          yarn test